# Generated by Django 4.1.2 on 2022-10-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_app', '0002_produto_quantidade_alter_categoria_nome_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_do_produto',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
