# Generated by Django 4.1.2 on 2022-10-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_app', '0003_alter_produto_desc_alter_produto_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor_da_compra', models.DecimalField(decimal_places=2, max_digits=150)),
                ('quantidade', models.IntegerField()),
                ('produtos', models.ManyToManyField(blank=True, to='vendas_app.produto')),
            ],
        ),
    ]
