# Generated by Django 4.1.2 on 2022-10-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_app', '0004_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='vendas', to='vendas_app.produto'),
        ),
    ]
