# Generated by Django 4.1.2 on 2022-10-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_app', '0005_alter_carrinho_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='valor_da_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=150),
        ),
    ]
