# Generated by Django 4.1.2 on 2022-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_app', '0006_alter_carrinho_valor_da_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='valor_da_compra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
